version: "3.8"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: runway_app
      POSTGRES_USER: runway_user
      POSTGRES_PASSWORD: runway_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
